#!/usr/bin/env python3
import argparse
import json
import re
from pathlib import Path
from urllib.parse import quote
from urllib.request import urlopen

from iiif_filename_rules import canonicalize_filename, is_normalized_filename


DEFAULT_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".tif",
    ".tiff",
    ".jp2",
    ".j2k",
    ".jpf",
    ".jpx",
    ".bmp",
    ".gif",
    ".webp",
}

KNOWN_TYPO_NORMALIZATIONS = (
    ("ADITIONAL_IMAGE", "ADDITIONAL_IMAGE"),
    ("ADITIONAL", "ADDITIONAL"),
    ("ADDITONAL", "ADDITIONAL"),
)

PRIMARY_PATTERN = re.compile(r"(^|_)PRIMARY_IMAGE($|_)", re.IGNORECASE)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate IIIF Presentation API v3 manifests from local image files."
    )
    parser.add_argument("--images-dir", default="images")
    parser.add_argument("--manifests-dir", default="manifests")
    parser.add_argument("--image-server-base", default="http://localhost:8182")
    parser.add_argument("--manifest-base", default="http://localhost:8182/manifests")
    parser.add_argument(
        "--extensions",
        nargs="*",
        default=sorted(DEFAULT_EXTENSIONS),
        help="Allowed image extensions, e.g. .jpg .tif .png",
    )
    parser.add_argument(
        "--enforce-normalized-identifiers",
        action="store_true",
        help="Fail objects that contain filenames not compliant with canonical identifier rules.",
    )
    parser.add_argument(
        "--identifier-map-output",
        default="_identifier_normalization_map.json",
        help="Output filename for normalization status report in manifests dir.",
    )
    parser.add_argument(
        "--qa-report",
        default="qa/reports/image_qa_report.json",
        help="Path to machine-readable QA report generated by qa_image_audit.py.",
    )
    parser.add_argument(
        "--require-qa-pass",
        action="store_true",
        help="Require qa-report status == pass before generating manifests.",
    )
    return parser.parse_args()


def normalize_name(name: str) -> str:
    out = name
    for old, new in KNOWN_TYPO_NORMALIZATIONS:
        out = re.sub(old, new, out, flags=re.IGNORECASE)
    return out


def get_object_id(stem: str):
    tokens = stem.split("_")
    if len(tokens) < 3:
        return None
    return "_".join(tokens[:3])


def is_primary_image(stem: str) -> bool:
    normalized = normalize_name(stem)
    return bool(PRIMARY_PATTERN.search(normalized))


def get_info(image_server_base: str, identifier: str):
    encoded = quote(identifier, safe="")
    info_url = f"{image_server_base}/iiif/3/{encoded}/info.json"
    with urlopen(info_url, timeout=30) as response:
        payload = json.loads(response.read().decode("utf-8"))
    width = int(payload["width"])
    height = int(payload["height"])
    if width <= 0 or height <= 0:
        raise ValueError(f"Invalid dimensions for {identifier}: {width}x{height}")
    return width, height, encoded, info_url


def main():
    args = parse_args()
    images_dir = Path(args.images_dir)
    manifests_dir = Path(args.manifests_dir)
    manifests_dir.mkdir(parents=True, exist_ok=True)

    if args.require_qa_pass:
        qa_path = Path(args.qa_report)
        if not qa_path.exists():
            raise FileNotFoundError(
                f"QA report not found: {qa_path}. Run qa_image_audit.py before manifest generation."
            )
        qa_payload = json.loads(qa_path.read_text(encoding="utf-8"))
        qa_status = qa_payload.get("status")
        if qa_status != "pass":
            raise RuntimeError(
                f"QA report status is '{qa_status}', expected 'pass'. Resolve findings before generating manifests."
            )

    allowed_ext = {ext.lower() if ext.startswith(".") else f".{ext.lower()}" for ext in args.extensions}
    files = sorted(
        [p for p in images_dir.iterdir() if p.is_file() and p.suffix.lower() in allowed_ext],
        key=lambda p: p.name,
    )

    groups = {}
    for path in files:
        object_id = get_object_id(path.stem)
        if not object_id:
            continue
        groups.setdefault(object_id, []).append(path)

    conflicts = []
    errors = []
    generated = 0
    skipped_conflicts = 0
    skipped_errors = 0
    normalization_map = []
    skipped_identifier_noncompliance = 0

    for object_id in sorted(groups.keys()):
        group_files = groups[object_id]
        primary_candidates = [p for p in group_files if is_primary_image(p.stem)]

        if len(primary_candidates) > 1:
            conflicts.append(
                {
                    "id": object_id,
                    "reason": "multiple PRIMARY_IMAGE files",
                    "files": sorted(p.name for p in primary_candidates),
                }
            )
            skipped_conflicts += 1
            continue

        if len(primary_candidates) == 1:
            primary = primary_candidates[0]
            ordered = [primary] + sorted(
                [p for p in group_files if p != primary], key=lambda p: p.name
            )
        else:
            ordered = sorted(group_files, key=lambda p: p.name)

        canvases = []
        manifest_has_error = False
        identifier_noncompliant = False

        for idx, file_path in enumerate(ordered, start=1):
            identifier = file_path.name
            canonical_identifier = canonicalize_filename(identifier)
            is_compliant = is_normalized_filename(identifier)
            normalization_map.append(
                {
                    "id": object_id,
                    "file": identifier,
                    "canonicalIdentifier": canonical_identifier,
                    "compliant": is_compliant,
                }
            )
            if args.enforce_normalized_identifiers and not is_compliant:
                errors.append(
                    {
                        "id": object_id,
                        "file": identifier,
                        "reason": "filename is not canonical",
                        "canonicalIdentifier": canonical_identifier,
                    }
                )
                identifier_noncompliant = True
                manifest_has_error = True
                break
            try:
                width, height, encoded, info_url = get_info(args.image_server_base, identifier)
            except Exception as exc:
                errors.append(
                    {
                        "id": object_id,
                        "file": identifier,
                        "reason": str(exc),
                    }
                )
                manifest_has_error = True
                break

            canvas_id = f"{args.manifest_base}/{object_id}/canvas/p{idx}"
            page_id = f"{args.manifest_base}/{object_id}/page/p{idx}"
            annotation_id = f"{args.manifest_base}/{object_id}/annotation/p{idx}"
            image_id = f"{args.image_server_base}/iiif/3/{encoded}/full/max/0/default.jpg"
            service_id = f"{args.image_server_base}/iiif/3/{encoded}"

            canvases.append(
                {
                    "id": canvas_id,
                    "type": "Canvas",
                    "width": width,
                    "height": height,
                    "label": {"none": [identifier]},
                    "items": [
                        {
                            "id": page_id,
                            "type": "AnnotationPage",
                            "items": [
                                {
                                    "id": annotation_id,
                                    "type": "Annotation",
                                    "motivation": "painting",
                                    "target": canvas_id,
                                    "body": {
                                        "id": image_id,
                                        "type": "Image",
                                        "format": "image/jpeg",
                                        "width": width,
                                        "height": height,
                                        "service": [
                                            {
                                                "id": service_id,
                                                "type": "ImageService3",
                                                "profile": "level2",
                                            }
                                        ],
                                    },
                                }
                            ],
                        }
                    ],
                }
            )

        if manifest_has_error:
            if identifier_noncompliant:
                skipped_identifier_noncompliance += 1
            skipped_errors += 1
            continue

        manifest = {
            "@context": "http://iiif.io/api/presentation/3/context.json",
            "id": f"{args.manifest_base}/{object_id}.json",
            "type": "Manifest",
            "label": {"none": [object_id]},
            "items": canvases,
        }

        output_path = manifests_dir / f"{object_id}.json"
        output_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
        generated += 1

    conflicts_path = manifests_dir / "_primary_image_conflicts.json"
    errors_path = manifests_dir / "_manifest_generation_errors.json"
    identifier_map_path = manifests_dir / args.identifier_map_output
    conflicts_path.write_text(json.dumps(conflicts, ensure_ascii=False, indent=2), encoding="utf-8")
    errors_path.write_text(json.dumps(errors, ensure_ascii=False, indent=2), encoding="utf-8")
    identifier_map_path.write_text(
        json.dumps(
            {
                "rulesVersion": "2026-02-25",
                "enforced": bool(args.enforce_normalized_identifiers),
                "items": normalization_map,
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )

    print(f"Generated manifests: {generated}")
    print(f"Skipped (multiple PRIMARY_IMAGE): {skipped_conflicts}")
    print(f"Skipped (errors): {skipped_errors}")
    print(f"Skipped (identifier noncompliance): {skipped_identifier_noncompliance}")
    print(f"Conflict report: {conflicts_path}")
    print(f"Error report: {errors_path}")
    print(f"Identifier map: {identifier_map_path}")


if __name__ == "__main__":
    main()
